# Generated by Django 2.0.2 on 2018-05-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airquality',
            name='AMB_TEMP',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='CH4',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='CO',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='NMHC',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='NO',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='NO2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='NOx',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='O3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='PH_RAIN',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='PM10',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='PM25',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='RAINFALL',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='RAIN_COND',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='RH',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='SO2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='THC',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='UVB',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='WD_HR',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='WIND_DIREC',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='WIND_SPEED',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='WS_HR',
            field=models.FloatField(),
        ),
    ]
